import { FatalError } from '@personio/api-sdk';

export const mockError: FatalError = {
  message: 'something bad happened',
  code: 500,
};

export const mockCandidates = [
  {
    id: 1,
    name: 'Alvin Satterfield',
    email: 'cornellbartell@connellyleannon.biz',
    birthDate: '1997-09-07',
    yearOfExperience: 5,
    positionApplied: 'Technician',
    applicationDate: '2018-07-02',
    status: 'rejected',
  },
  {
    id: 2,
    name: 'Colette Morar',
    email: 'corinnestark@pacocha.co',
    birthDate: '1998-08-03',
    yearOfExperience: 3,
    positionApplied: 'Designer',
    applicationDate: '2017-11-18',
    status: 'waiting',
  },
  {
    id: 3,
    name: 'Rosalind Rath DDS',
    email: 'sandyankunding@marks.io',
    birthDate: '1980-03-28',
    yearOfExperience: 15,
    positionApplied: 'Orchestrator',
    applicationDate: '2018-01-31',
    status: 'approved',
  },
  {
    id: 4,
    name: 'Cyrstal Kunze',
    email: 'lavernokon@stroman.name',
    birthDate: '1997-10-30',
    yearOfExperience: 8,
    positionApplied: 'Analyst',
    applicationDate: '2018-09-12',
    status: 'rejected',
  },
  {
    id: 5,
    name: 'Henrietta Fisher V',
    email: 'lewis@sipes.biz',
    birthDate: '1974-09-14',
    yearOfExperience: 14,
    positionApplied: 'Producer',
    applicationDate: '2018-04-25',
    status: 'waiting',
  },
  {
    id: 6,
    name: 'Michal Kiehn Sr.',
    email: 'ruelmarks@prohaska.co',
    birthDate: '1976-08-04',
    yearOfExperience: 1,
    positionApplied: 'Planner',
    applicationDate: '2018-04-05',
    status: 'rejected',
  },
  {
    id: 7,
    name: 'Lavonda Murazik',
    email: 'mayesimonis@white.name',
    birthDate: '1984-04-25',
    yearOfExperience: 6,
    positionApplied: 'Administrator',
    applicationDate: '2018-10-06',
    status: 'waiting',
  },
  {
    id: 8,
    name: 'Herman Altenwerth',
    email: 'wavavonrueden@brekkecasper.org',
    birthDate: '1996-08-08',
    yearOfExperience: 2,
    positionApplied: 'Liaison',
    applicationDate: '2018-09-14',
    status: 'waiting',
  },
  {
    id: 9,
    name: 'Ernestina Dicki',
    email: 'lawrencekunze@pouros.io',
    birthDate: '1971-09-01',
    yearOfExperience: 14,
    positionApplied: 'Associate',
    applicationDate: '2018-07-13',
    status: 'approved',
  },
  {
    id: 10,
    name: 'Deedee Kuhic',
    email: 'karisa@mertz.co',
    birthDate: '1973-08-30',
    yearOfExperience: 2,
    positionApplied: 'Strategist',
    applicationDate: '2018-10-08',
    status: 'waiting',
  },
  {
    id: 11,
    name: 'Carmela Hilll Sr.',
    email: 'hermelindalang@barrows.org',
    birthDate: '1984-10-04',
    yearOfExperience: 11,
    positionApplied: 'Assistant',
    applicationDate: '2018-10-10',
    status: 'waiting',
  },
  {
    id: 12,
    name: 'Brandon Hilll',
    email: 'vondalangosh@bosco.org',
    birthDate: '1986-02-03',
    yearOfExperience: 5,
    positionApplied: 'Representative',
    applicationDate: '2018-04-11',
    status: 'rejected',
  },
  {
    id: 13,
    name: 'Sam Donnelly',
    email: 'marya@cronin.com',
    birthDate: '1994-04-18',
    yearOfExperience: 5,
    positionApplied: 'Assistant',
    applicationDate: '2018-10-15',
    status: 'waiting',
  },
  {
    id: 14,
    name: 'Mr. Rolando Davis',
    email: 'blainecormier@jacobslangworth.biz',
    birthDate: '1977-11-30',
    yearOfExperience: 15,
    positionApplied: 'Developer',
    applicationDate: '2018-02-14',
    status: 'rejected',
  },
  {
    id: 15,
    name: 'Gay Ullrich II',
    email: 'denis@mills.info',
    birthDate: '1972-05-26',
    yearOfExperience: 7,
    positionApplied: 'Executive',
    applicationDate: '2018-02-02',
    status: 'approved',
  },
  {
    id: 16,
    name: 'Ollie Bednar PhD',
    email: 'chong@gleichner.net',
    birthDate: '1979-07-09',
    yearOfExperience: 3,
    positionApplied: 'Executive',
    applicationDate: '2017-11-11',
    status: 'rejected',
  },
  {
    id: 17,
    name: 'Gonzalo Mueller',
    email: 'jonathanwilderman@creminschumm.org',
    birthDate: '1973-03-05',
    yearOfExperience: 5,
    positionApplied: 'Agent',
    applicationDate: '2018-03-21',
    status: 'rejected',
  },
  {
    id: 18,
    name: 'Kristopher Mills',
    email: 'latiaschowalter@hammes.com',
    birthDate: '1980-02-19',
    yearOfExperience: 11,
    positionApplied: 'Manager',
    applicationDate: '2018-09-02',
    status: 'approved',
  },
  {
    id: 19,
    name: 'Filiberto Williamson',
    email: 'wanetta@ruecker.co',
    birthDate: '1976-05-14',
    yearOfExperience: 10,
    positionApplied: 'Orchestrator',
    applicationDate: '2018-07-30',
    status: 'approved',
  },
  {
    id: 20,
    name: 'Ester Treutel',
    email: 'hugh@kuvalis.net',
    birthDate: '1995-12-02',
    yearOfExperience: 4,
    positionApplied: 'Manager',
    applicationDate: '2018-01-20',
    status: 'waiting',
  },
  {
    id: 21,
    name: 'Marlys Larkin',
    email: 'lowell@ritchie.org',
    birthDate: '1986-01-26',
    yearOfExperience: 4,
    positionApplied: 'Liaison',
    applicationDate: '2018-01-25',
    status: 'approved',
  },
  {
    id: 22,
    name: 'Kitty Tillman',
    email: 'shirleyschumm@blickhintz.com',
    birthDate: '1978-12-02',
    yearOfExperience: 4,
    positionApplied: 'Coordinator',
    applicationDate: '2018-05-16',
    status: 'waiting',
  },
  {
    id: 23,
    name: 'Felton Kovacek',
    email: 'bernettayost@greenholt.biz',
    birthDate: '1977-10-30',
    yearOfExperience: 13,
    positionApplied: 'Director',
    applicationDate: '2018-01-09',
    status: 'rejected',
  },
  {
    id: 24,
    name: 'Larry Bruen',
    email: 'molly@harvey.name',
    birthDate: '1995-01-08',
    yearOfExperience: 1,
    positionApplied: 'Facilitator',
    applicationDate: '2018-10-15',
    status: 'rejected',
  },
  {
    id: 25,
    name: 'Stephan Trantow',
    email: 'henriette@lowe.io',
    birthDate: '2000-09-15',
    yearOfExperience: 10,
    positionApplied: 'Architect',
    applicationDate: '2018-03-07',
    status: 'waiting',
  },
  {
    id: 26,
    name: 'Jacquelynn Bernhard II',
    email: 'annisvandervort@watsica.io',
    birthDate: '1981-02-20',
    yearOfExperience: 13,
    positionApplied: 'Agent',
    applicationDate: '2018-09-24',
    status: 'waiting',
  },
  {
    id: 27,
    name: 'Winston Glover Jr.',
    email: 'saulschneider@hamillbarton.co',
    birthDate: '1980-12-12',
    yearOfExperience: 13,
    positionApplied: 'Officer',
    applicationDate: '2018-05-30',
    status: 'rejected',
  },
  {
    id: 28,
    name: 'Ross Hagenes MD',
    email: 'dakotacrona@lang.info',
    birthDate: '1970-02-02',
    yearOfExperience: 14,
    positionApplied: 'Developer',
    applicationDate: '2018-07-08',
    status: 'approved',
  },
  {
    id: 29,
    name: 'Judson Keebler',
    email: 'dinalynch@cruickshanklang.io',
    birthDate: '1974-11-03',
    yearOfExperience: 9,
    positionApplied: 'Consultant',
    applicationDate: '2018-02-08',
    status: 'waiting',
  },
  {
    id: 30,
    name: 'Avery Ruecker',
    email: 'bailey@greenholt.biz',
    birthDate: '1995-12-29',
    yearOfExperience: 4,
    positionApplied: 'Director',
    applicationDate: '2018-06-02',
    status: 'rejected',
  },
  {
    id: 31,
    name: 'Nelson Miller DDS',
    email: 'amado@abbott.org',
    birthDate: '1976-10-09',
    yearOfExperience: 7,
    positionApplied: 'Agent',
    applicationDate: '2018-10-03',
    status: 'approved',
  },
  {
    id: 32,
    name: 'Sung Rempel IV',
    email: 'sammieokuneva@koelpinlangosh.info',
    birthDate: '1995-01-09',
    yearOfExperience: 14,
    positionApplied: 'Analyst',
    applicationDate: '2018-05-22',
    status: 'rejected',
  },
  {
    id: 33,
    name: 'Dominica Haley',
    email: 'scottyrath@orn.com',
    birthDate: '1973-08-19',
    yearOfExperience: 14,
    positionApplied: 'Consultant',
    applicationDate: '2018-08-04',
    status: 'approved',
  },
  {
    id: 34,
    name: 'Cordell Bogisich',
    email: 'gerryhane@mayer.name',
    birthDate: '1983-07-04',
    yearOfExperience: 12,
    positionApplied: 'Architect',
    applicationDate: '2018-08-26',
    status: 'waiting',
  },
  {
    id: 35,
    name: 'Miss Jerrold Prohaska',
    email: 'emiliahaley@hansenschimmel.name',
    birthDate: '1977-10-15',
    yearOfExperience: 7,
    positionApplied: 'Strategist',
    applicationDate: '2017-10-17',
    status: 'approved',
  },
  {
    id: 36,
    name: 'Carlton Kuvalis',
    email: 'yoshie@yundt.io',
    birthDate: '1996-09-07',
    yearOfExperience: 14,
    positionApplied: 'Supervisor',
    applicationDate: '2018-01-02',
    status: 'approved',
  },
  {
    id: 37,
    name: 'Trinidad Hamill II',
    email: 'mckinley@runolfon.name',
    birthDate: '1970-12-05',
    yearOfExperience: 4,
    positionApplied: 'Liaison',
    applicationDate: '2018-03-13',
    status: 'approved',
  },
  {
    id: 38,
    name: 'Gertie Haley',
    email: 'blancahermiston@pacocha.com',
    birthDate: '1983-04-20',
    yearOfExperience: 8,
    positionApplied: 'Administrator',
    applicationDate: '2018-05-25',
    status: 'waiting',
  },
  {
    id: 39,
    name: 'Lucinda Trantow',
    email: 'milan@bernierdonnelly.io',
    birthDate: '1999-07-15',
    yearOfExperience: 1,
    positionApplied: 'Executive',
    applicationDate: '2018-06-08',
    status: 'approved',
  },
  {
    id: 40,
    name: 'Richard Frami',
    email: 'omar@labadie.org',
    birthDate: '1985-02-11',
    yearOfExperience: 3,
    positionApplied: 'Liaison',
    applicationDate: '2018-09-17',
    status: 'waiting',
  },
  {
    id: 41,
    name: 'Brant Marvin',
    email: 'harry@greenholt.io',
    birthDate: '1982-08-19',
    yearOfExperience: 4,
    positionApplied: 'Liaison',
    applicationDate: '2018-03-11',
    status: 'waiting',
  },
  {
    id: 42,
    name: 'Grant Schuppe',
    email: 'curtisbernhard@dubuque.co',
    birthDate: '1973-07-18',
    yearOfExperience: 7,
    positionApplied: 'Administrator',
    applicationDate: '2017-12-20',
    status: 'waiting',
  },
  {
    id: 43,
    name: 'Gaston Homenick',
    email: 'buena@schuppe.info',
    birthDate: '1973-08-30',
    yearOfExperience: 13,
    positionApplied: 'Producer',
    applicationDate: '2018-08-27',
    status: 'rejected',
  },
  {
    id: 44,
    name: 'Dr. Denyse Walsh',
    email: 'lynna@donnelly.net',
    birthDate: '1980-10-16',
    yearOfExperience: 1,
    positionApplied: 'Orchestrator',
    applicationDate: '2018-04-25',
    status: 'approved',
  },
  {
    id: 45,
    name: 'Toshiko Gusikowski',
    email: 'davismueller@muller.info',
    birthDate: '1986-05-14',
    yearOfExperience: 4,
    positionApplied: 'Representative',
    applicationDate: '2018-10-15',
    status: 'waiting',
  },
  {
    id: 46,
    name: 'Jarred Donnelly Jr.',
    email: 'jarrodrolfson@baumbachlesch.org',
    birthDate: '1990-07-09',
    yearOfExperience: 4,
    positionApplied: 'Designer',
    applicationDate: '2018-01-20',
    status: 'waiting',
  },
  {
    id: 47,
    name: 'Barabara Rolfson',
    email: 'nicolette@swiftframi.info',
    birthDate: '1974-06-30',
    yearOfExperience: 9,
    positionApplied: 'Manager',
    applicationDate: '2018-08-19',
    status: 'waiting',
  },
  {
    id: 48,
    name: 'Mrs. Quentin Batz',
    email: 'kermit@smitham.org',
    birthDate: '1990-11-21',
    yearOfExperience: 7,
    positionApplied: 'Planner',
    applicationDate: '2018-02-08',
    status: 'rejected',
  },
  {
    id: 49,
    name: 'Corey Kunze Jr.',
    email: 'leroy@brakustorphy.co',
    birthDate: '1971-07-30',
    yearOfExperience: 7,
    positionApplied: 'Administrator',
    applicationDate: '2018-02-05',
    status: 'rejected',
  },
  {
    id: 50,
    name: 'Lamar McDermott',
    email: 'blair@kunderath.org',
    birthDate: '1989-10-03',
    yearOfExperience: 10,
    positionApplied: 'Architect',
    applicationDate: '2018-02-11',
    status: 'waiting',
  },
  {
    id: 51,
    name: 'Kami Jerde',
    email: 'alexisjones@handklein.io',
    birthDate: '1968-12-09',
    yearOfExperience: 1,
    positionApplied: 'Engineer',
    applicationDate: '2018-07-25',
    status: 'waiting',
  },
  {
    id: 52,
    name: 'Eloise Goyette',
    email: 'walter@larsonrobel.co',
    birthDate: '1993-06-09',
    yearOfExperience: 1,
    positionApplied: 'Assistant',
    applicationDate: '2018-09-12',
    status: 'rejected',
  },
  {
    id: 53,
    name: 'Weston Welch',
    email: 'josef@carterrodriguez.net',
    birthDate: '1989-08-06',
    yearOfExperience: 8,
    positionApplied: 'Officer',
    applicationDate: '2017-12-25',
    status: 'approved',
  },
  {
    id: 54,
    name: 'Ms. Ignacio Olson',
    email: 'claude@abbott.biz',
    birthDate: '1972-12-18',
    yearOfExperience: 8,
    positionApplied: 'Orchestrator',
    applicationDate: '2018-04-12',
    status: 'approved',
  },
  {
    id: 55,
    name: 'Mr. Fausto Bednar',
    email: 'gilberte@mills.co',
    birthDate: '1975-10-27',
    yearOfExperience: 10,
    positionApplied: 'Administrator',
    applicationDate: '2018-07-29',
    status: 'waiting',
  },
  {
    id: 56,
    name: 'Jarod Funk',
    email: 'todd@simonis.info',
    birthDate: '1970-04-03',
    yearOfExperience: 9,
    positionApplied: 'Supervisor',
    applicationDate: '2018-06-07',
    status: 'approved',
  },
  {
    id: 57,
    name: 'Lewis Mann',
    email: 'tameika@powlowski.com',
    birthDate: '1971-04-14',
    yearOfExperience: 9,
    positionApplied: 'Manager',
    applicationDate: '2018-06-16',
    status: 'approved',
  },
  {
    id: 58,
    name: 'Marcelina Powlowski I',
    email: 'josef@rice.io',
    birthDate: '1985-11-27',
    yearOfExperience: 10,
    positionApplied: 'Associate',
    applicationDate: '2018-05-10',
    status: 'approved',
  },
  {
    id: 59,
    name: 'Ms. Reda Murazik',
    email: 'jolynn@ebertmonahan.io',
    birthDate: '1973-02-14',
    yearOfExperience: 8,
    positionApplied: 'Specialist',
    applicationDate: '2018-06-16',
    status: 'rejected',
  },
  {
    id: 60,
    name: 'Terrance Boyle Jr.',
    email: 'paul@medhurstgraham.name',
    birthDate: '1996-07-12',
    yearOfExperience: 14,
    positionApplied: 'Administrator',
    applicationDate: '2018-06-14',
    status: 'rejected',
  },
  {
    id: 61,
    name: 'Leota Heaney',
    email: 'mandalesch@daugherty.biz',
    birthDate: '1991-07-09',
    yearOfExperience: 15,
    positionApplied: 'Strategist',
    applicationDate: '2018-01-24',
    status: 'waiting',
  },
  {
    id: 62,
    name: 'Madeleine Sauer',
    email: 'lenore@mcdermottrenner.co',
    birthDate: '1997-05-14',
    yearOfExperience: 6,
    positionApplied: 'Engineer',
    applicationDate: '2018-01-05',
    status: 'waiting',
  },
  {
    id: 63,
    name: 'Edward Pouros',
    email: 'robbiyundt@labadie.info',
    birthDate: '2000-05-26',
    yearOfExperience: 8,
    positionApplied: 'Consultant',
    applicationDate: '2018-08-08',
    status: 'waiting',
  },
  {
    id: 64,
    name: 'Rex Fisher V',
    email: 'matildegerlach@friesen.info',
    birthDate: '1994-12-19',
    yearOfExperience: 11,
    positionApplied: 'Analyst',
    applicationDate: '2018-04-19',
    status: 'approved',
  },
  {
    id: 65,
    name: 'Odell Roberts',
    email: 'lorna@thiel.org',
    birthDate: '1981-12-07',
    yearOfExperience: 13,
    positionApplied: 'Representative',
    applicationDate: '2018-07-02',
    status: 'approved',
  },
  {
    id: 66,
    name: 'Rayford Bogan',
    email: 'coyrempel@murazik.io',
    birthDate: '1978-05-09',
    yearOfExperience: 14,
    positionApplied: 'Architect',
    applicationDate: '2018-03-12',
    status: 'waiting',
  },
  {
    id: 67,
    name: 'Julio Borer',
    email: 'suanne@krajcik.co',
    birthDate: '1973-12-19',
    yearOfExperience: 8,
    positionApplied: 'Manager',
    applicationDate: '2018-03-18',
    status: 'waiting',
  },
  {
    id: 68,
    name: 'Ms. Helga Hessel',
    email: 'ariana@beahan.biz',
    birthDate: '1994-05-16',
    yearOfExperience: 15,
    positionApplied: 'Representative',
    applicationDate: '2017-11-11',
    status: 'approved',
  },
  {
    id: 69,
    name: 'Ms. Harold Wolff',
    email: 'john@kub.org',
    birthDate: '1991-10-26',
    yearOfExperience: 14,
    positionApplied: 'Technician',
    applicationDate: '2018-09-03',
    status: 'rejected',
  },
  {
    id: 70,
    name: 'Ms. Noah Quitzon',
    email: 'augustus@erdman.biz',
    birthDate: '1972-06-16',
    yearOfExperience: 9,
    positionApplied: 'Producer',
    applicationDate: '2017-11-13',
    status: 'waiting',
  },
  {
    id: 71,
    name: 'Lizabeth Hoeger',
    email: 'rosendobashirian@zulaufzieme.com',
    birthDate: '1972-05-06',
    yearOfExperience: 9,
    positionApplied: 'Manager',
    applicationDate: '2017-12-30',
    status: 'rejected',
  },
  {
    id: 72,
    name: 'Cristy Raynor',
    email: 'porfiriohansen@schustermayer.org',
    birthDate: '1996-08-15',
    yearOfExperience: 14,
    positionApplied: 'Developer',
    applicationDate: '2018-10-09',
    status: 'rejected',
  },
  {
    id: 73,
    name: 'Miss Miles Dietrich',
    email: 'moriahjohnson@nicolasweinat.io',
    birthDate: '1981-07-29',
    yearOfExperience: 9,
    positionApplied: 'Agent',
    applicationDate: '2018-10-05',
    status: 'waiting',
  },
  {
    id: 74,
    name: 'Jordon Cremin',
    email: 'zita@gutmann.info',
    birthDate: '1995-02-05',
    yearOfExperience: 9,
    positionApplied: 'Representative',
    applicationDate: '2018-04-04',
    status: 'waiting',
  },
  {
    id: 75,
    name: 'Marcel Terry',
    email: 'berta@lemke.io',
    birthDate: '1980-07-31',
    yearOfExperience: 8,
    positionApplied: 'Liaison',
    applicationDate: '2018-01-26',
    status: 'approved',
  },
  {
    id: 76,
    name: 'Gerardo Hills',
    email: 'silashand@reichelkeler.org',
    birthDate: '1977-12-03',
    yearOfExperience: 6,
    positionApplied: 'Specialist',
    applicationDate: '2017-11-30',
    status: 'rejected',
  },
  {
    id: 77,
    name: 'Sung Towne',
    email: 'kai@volkmanbartoletti.io',
    birthDate: '1991-06-02',
    yearOfExperience: 4,
    positionApplied: 'Strategist',
    applicationDate: '2018-09-01',
    status: 'approved',
  },
  {
    id: 78,
    name: 'Ms. Henry Nikolaus',
    email: 'thomasbrekke@williamson.biz',
    birthDate: '1990-07-04',
    yearOfExperience: 6,
    positionApplied: 'Specialist',
    applicationDate: '2018-03-28',
    status: 'waiting',
  },
  {
    id: 79,
    name: 'Lauralee Turcotte PhD',
    email: 'katheydoyle@graham.org',
    birthDate: '1991-11-21',
    yearOfExperience: 12,
    positionApplied: 'Facilitator',
    applicationDate: '2018-02-26',
    status: 'rejected',
  },
  {
    id: 80,
    name: 'Carola Weber',
    email: 'eugene@turner.io',
    birthDate: '1991-02-06',
    yearOfExperience: 12,
    positionApplied: 'Facilitator',
    applicationDate: '2018-10-08',
    status: 'rejected',
  },
  {
    id: 81,
    name: 'Zola Nicolas V',
    email: 'thaddeus@aufderhar.name',
    birthDate: '1990-07-19',
    yearOfExperience: 8,
    positionApplied: 'Assistant',
    applicationDate: '2017-12-10',
    status: 'approved',
  },
  {
    id: 82,
    name: 'Jerold Wiza',
    email: 'gladys@jerdeward.biz',
    birthDate: '1983-08-02',
    yearOfExperience: 6,
    positionApplied: 'Director',
    applicationDate: '2018-09-07',
    status: 'approved',
  },
  {
    id: 83,
    name: 'Dr. Erna Kuvalis',
    email: 'chanellefunk@schamberger.net',
    birthDate: '1989-01-15',
    yearOfExperience: 1,
    positionApplied: 'Coordinator',
    applicationDate: '2018-01-10',
    status: 'waiting',
  },
  {
    id: 84,
    name: 'Berniece Walker IV',
    email: 'eugenio@bergstrom.org',
    birthDate: '1971-04-21',
    yearOfExperience: 13,
    positionApplied: 'Technician',
    applicationDate: '2018-05-15',
    status: 'approved',
  },
  {
    id: 85,
    name: 'Dr. Miles Windler',
    email: 'rociohane@krajcik.com',
    birthDate: '1983-10-05',
    yearOfExperience: 4,
    positionApplied: 'Developer',
    applicationDate: '2017-11-24',
    status: 'approved',
  },
  {
    id: 86,
    name: 'Gil Feil I',
    email: 'zitalabadie@whitejaskolski.com',
    birthDate: '1986-10-03',
    yearOfExperience: 8,
    positionApplied: 'Consultant',
    applicationDate: '2018-04-11',
    status: 'waiting',
  },
  {
    id: 87,
    name: 'Irish Cummerata',
    email: 'jeffersonnolan@kiehnrunolfsdottir.com',
    birthDate: '1994-09-30',
    yearOfExperience: 8,
    positionApplied: 'Analyst',
    applicationDate: '2018-09-29',
    status: 'rejected',
  },
  {
    id: 88,
    name: 'Darwin Pfeffer I',
    email: 'mack@yost.name',
    birthDate: '1994-12-14',
    yearOfExperience: 8,
    positionApplied: 'Liaison',
    applicationDate: '2018-03-13',
    status: 'waiting',
  },
  {
    id: 89,
    name: 'Vergie Rath',
    email: 'joettamitchell@willms.info',
    birthDate: '1977-11-12',
    yearOfExperience: 8,
    positionApplied: 'Supervisor',
    applicationDate: '2017-11-10',
    status: 'approved',
  },
  {
    id: 90,
    name: 'Malisa Rath DVM',
    email: 'enedinalangosh@daughertylockman.co',
    birthDate: '1991-05-01',
    yearOfExperience: 3,
    positionApplied: 'Officer',
    applicationDate: '2018-01-30',
    status: 'rejected',
  },
  {
    id: 91,
    name: 'Mammie Beahan',
    email: 'oziekemmer@reichel.co',
    birthDate: '1975-01-29',
    yearOfExperience: 4,
    positionApplied: 'Analyst',
    applicationDate: '2017-12-24',
    status: 'waiting',
  },
  {
    id: 92,
    name: 'Chrystal Bergnaum',
    email: 'koryvon@predovicbalistreri.io',
    birthDate: '1987-11-02',
    yearOfExperience: 4,
    positionApplied: 'Assistant',
    applicationDate: '2018-04-20',
    status: 'approved',
  },
  {
    id: 93,
    name: 'Mrs. Roderick Schulist',
    email: 'stacy@raustoltenberg.net',
    birthDate: '1991-10-13',
    yearOfExperience: 4,
    positionApplied: 'Analyst',
    applicationDate: '2018-07-15',
    status: 'approved',
  },
  {
    id: 94,
    name: 'Sandy Johnson',
    email: 'lukeshields@fahey.biz',
    birthDate: '1992-05-16',
    yearOfExperience: 2,
    positionApplied: 'Facilitator',
    applicationDate: '2018-01-02',
    status: 'approved',
  },
  {
    id: 95,
    name: 'Mr. Lavonda Russel',
    email: 'sharda@batzemard.biz',
    birthDate: '1971-03-10',
    yearOfExperience: 4,
    positionApplied: 'Engineer',
    applicationDate: '2018-03-18',
    status: 'waiting',
  },
  {
    id: 96,
    name: 'Miss Donovan Deckow',
    email: 'maxwell@haley.io',
    birthDate: '1982-06-25',
    yearOfExperience: 1,
    positionApplied: 'Officer',
    applicationDate: '2017-12-02',
    status: 'rejected',
  },
  {
    id: 97,
    name: 'Shanon Lesch',
    email: 'harlandhaley@kris.net',
    birthDate: '1970-12-11',
    yearOfExperience: 14,
    positionApplied: 'Manager',
    applicationDate: '2018-04-22',
    status: 'rejected',
  },
  {
    id: 98,
    name: 'Miss Bertie Fay',
    email: 'cherly@gottlieb.org',
    birthDate: '1987-05-17',
    yearOfExperience: 10,
    positionApplied: 'Representative',
    applicationDate: '2018-06-15',
    status: 'approved',
  },
  {
    id: 99,
    name: 'Bob Ledner',
    email: 'maragaretprosacco@oconnellschaden.com',
    birthDate: '1972-11-18',
    yearOfExperience: 4,
    positionApplied: 'Facilitator',
    applicationDate: '2018-07-24',
    status: 'rejected',
  },
  {
    id: 100,
    name: 'Ron Green',
    email: 'shawannalueilwitz@spencer.com',
    birthDate: '1995-05-10',
    yearOfExperience: 8,
    positionApplied: 'Administrator',
    applicationDate: '2018-06-23',
    status: 'waiting',
  },
  {
    id: 101,
    name: 'Delbert Monahan Sr.',
    email: 'marlaruecker@schummwillms.co',
    birthDate: '1969-04-16',
    yearOfExperience: 11,
    positionApplied: 'Coordinator',
    applicationDate: '2018-09-27',
    status: 'waiting',
  },
  {
    id: 102,
    name: 'Mike Gerhold',
    email: 'bartonmann@oconner.com',
    birthDate: '2000-08-09',
    yearOfExperience: 2,
    positionApplied: 'Administrator',
    applicationDate: '2018-02-14',
    status: 'rejected',
  },
  {
    id: 103,
    name: 'Yun Ward',
    email: 'grant@gutkowskiparker.info',
    birthDate: '1995-03-30',
    yearOfExperience: 5,
    positionApplied: 'Designer',
    applicationDate: '2018-01-05',
    status: 'rejected',
  },
  {
    id: 104,
    name: 'Tom Wiza I',
    email: 'leigh@schoen.name',
    birthDate: '1972-06-25',
    yearOfExperience: 2,
    positionApplied: 'Coordinator',
    applicationDate: '2018-07-08',
    status: 'waiting',
  },
  {
    id: 105,
    name: 'Donn Haag II',
    email: 'aronsatterfield@pacochahuels.com',
    birthDate: '1976-10-10',
    yearOfExperience: 4,
    positionApplied: 'Assistant',
    applicationDate: '2017-11-26',
    status: 'approved',
  },
  {
    id: 106,
    name: 'Ms. Colin Rippin',
    email: 'clarinecarroll@mcglynn.org',
    birthDate: '1990-08-08',
    yearOfExperience: 13,
    positionApplied: 'Assistant',
    applicationDate: '2018-01-24',
    status: 'rejected',
  },
  {
    id: 107,
    name: 'Elena Jakubowski',
    email: 'sumikoluettgen@lakin.com',
    birthDate: '1983-05-27',
    yearOfExperience: 6,
    positionApplied: 'Engineer',
    applicationDate: '2018-09-28',
    status: 'rejected',
  },
  {
    id: 108,
    name: 'Mrs. Ricardo Ondricka',
    email: 'forrestkuhn@strosin.name',
    birthDate: '1975-04-07',
    yearOfExperience: 11,
    positionApplied: 'Designer',
    applicationDate: '2018-03-15',
    status: 'waiting',
  },
  {
    id: 109,
    name: 'Dan Kuhic IV',
    email: 'houston@okon.net',
    birthDate: '1971-09-23',
    yearOfExperience: 14,
    positionApplied: 'Specialist',
    applicationDate: '2017-11-11',
    status: 'waiting',
  },
  {
    id: 110,
    name: 'Ozell Haag',
    email: 'shellidenesik@auer.com',
    birthDate: '1993-07-06',
    yearOfExperience: 5,
    positionApplied: 'Technician',
    applicationDate: '2017-11-13',
    status: 'approved',
  },
  {
    id: 111,
    name: 'Emilio Rau DVM',
    email: 'thuluettgen@harbermertz.org',
    birthDate: '1973-11-27',
    yearOfExperience: 11,
    positionApplied: 'Manager',
    applicationDate: '2018-02-14',
    status: 'waiting',
  },
  {
    id: 112,
    name: "Claretha O'Connell",
    email: 'sammierosenbaum@hand.org',
    birthDate: '1988-04-11',
    yearOfExperience: 10,
    positionApplied: 'Producer',
    applicationDate: '2018-08-20',
    status: 'approved',
  },
  {
    id: 113,
    name: 'Korey Thiel',
    email: 'lauricebartoletti@welch.com',
    birthDate: '1994-11-08',
    yearOfExperience: 9,
    positionApplied: 'Engineer',
    applicationDate: '2017-11-21',
    status: 'waiting',
  },
  {
    id: 114,
    name: 'Isidra Huel Sr.',
    email: 'eliasjohnson@torp.biz',
    birthDate: '1998-10-03',
    yearOfExperience: 12,
    positionApplied: 'Specialist',
    applicationDate: '2017-10-16',
    status: 'approved',
  },
  {
    id: 115,
    name: 'Jesus Gusikowski',
    email: 'bongdach@gutkowski.biz',
    birthDate: '1990-03-04',
    yearOfExperience: 2,
    positionApplied: 'Facilitator',
    applicationDate: '2018-10-03',
    status: 'rejected',
  },
  {
    id: 116,
    name: 'Bradford Lockman',
    email: 'danaherzog@fahey.com',
    birthDate: '1973-07-10',
    yearOfExperience: 2,
    positionApplied: 'Officer',
    applicationDate: '2017-12-01',
    status: 'approved',
  },
  {
    id: 117,
    name: 'Dewayne Beier III',
    email: 'jackqueline@collins.co',
    birthDate: '1973-09-21',
    yearOfExperience: 1,
    positionApplied: 'Administrator',
    applicationDate: '2018-10-15',
    status: 'waiting',
  },
  {
    id: 118,
    name: 'Lucy Feest',
    email: 'elisahills@kertzmannoberbrunner.info',
    birthDate: '1996-12-29',
    yearOfExperience: 13,
    positionApplied: 'Director',
    applicationDate: '2018-04-15',
    status: 'waiting',
  },
  {
    id: 119,
    name: 'Daphine Wilderman',
    email: 'jennine@larsonwuckert.info',
    birthDate: '1986-02-01',
    yearOfExperience: 8,
    positionApplied: 'Supervisor',
    applicationDate: '2018-06-19',
    status: 'rejected',
  },
  {
    id: 120,
    name: 'Miss Levi Dicki',
    email: 'cindy@fay.io',
    birthDate: '1997-04-15',
    yearOfExperience: 5,
    positionApplied: 'Analyst',
    applicationDate: '2017-12-06',
    status: 'approved',
  },
  {
    id: 121,
    name: 'Miss Trinidad Skiles',
    email: 'ryankertzmann@dietrich.biz',
    birthDate: '1971-06-29',
    yearOfExperience: 1,
    positionApplied: 'Executive',
    applicationDate: '2018-04-23',
    status: 'rejected',
  },
  {
    id: 122,
    name: 'Vince Treutel MD',
    email: 'judebins@langworthhartmann.co',
    birthDate: '1980-10-18',
    yearOfExperience: 13,
    positionApplied: 'Specialist',
    applicationDate: '2018-05-09',
    status: 'approved',
  },
  {
    id: 123,
    name: 'Rae Watsica',
    email: 'billy@kub.co',
    birthDate: '1983-02-21',
    yearOfExperience: 4,
    positionApplied: 'Consultant',
    applicationDate: '2018-05-27',
    status: 'waiting',
  },
  {
    id: 124,
    name: 'Dr. Lamont Champlin',
    email: 'bretsanford@carter.info',
    birthDate: '1979-02-18',
    yearOfExperience: 3,
    positionApplied: 'Specialist',
    applicationDate: '2017-10-31',
    status: 'approved',
  },
  {
    id: 125,
    name: 'Arnulfo Weimann',
    email: 'marenlakin@torphykeler.info',
    birthDate: '1979-01-09',
    yearOfExperience: 2,
    positionApplied: 'Assistant',
    applicationDate: '2018-01-04',
    status: 'waiting',
  },
  {
    id: 126,
    name: 'Celestina Hayes',
    email: 'corey@lynch.info',
    birthDate: '1981-04-22',
    yearOfExperience: 13,
    positionApplied: 'Orchestrator',
    applicationDate: '2018-04-03',
    status: 'approved',
  },
  {
    id: 127,
    name: "Miss Marilee O'Connell",
    email: 'maya@kerluke.biz',
    birthDate: '2000-09-14',
    yearOfExperience: 10,
    positionApplied: 'Orchestrator',
    applicationDate: '2018-06-28',
    status: 'approved',
  },
  {
    id: 128,
    name: 'Dr. Calvin Krajcik',
    email: 'quentin@blicklegros.net',
    birthDate: '1999-07-24',
    yearOfExperience: 1,
    positionApplied: 'Planner',
    applicationDate: '2018-03-10',
    status: 'approved',
  },
  {
    id: 129,
    name: 'Nicolasa Rolfson',
    email: 'siu@schuppeglover.com',
    birthDate: '1993-04-16',
    yearOfExperience: 11,
    positionApplied: 'Executive',
    applicationDate: '2018-10-01',
    status: 'approved',
  },
  {
    id: 130,
    name: 'Eugenio Bode',
    email: 'michawuckert@waltermoore.io',
    birthDate: '1987-08-13',
    yearOfExperience: 13,
    positionApplied: 'Manager',
    applicationDate: '2017-11-14',
    status: 'waiting',
  },
  {
    id: 131,
    name: 'Collin Douglas',
    email: 'sharlachamplin@beahan.name',
    birthDate: '1997-11-21',
    yearOfExperience: 4,
    positionApplied: 'Representative',
    applicationDate: '2018-04-02',
    status: 'rejected',
  },
  {
    id: 132,
    name: 'Vincent Fritsch',
    email: 'kyungnikolaus@towne.name',
    birthDate: '1988-04-02',
    yearOfExperience: 1,
    positionApplied: 'Specialist',
    applicationDate: '2017-11-28',
    status: 'waiting',
  },
  {
    id: 133,
    name: 'Marcene Rath',
    email: 'anasanford@mcclure.info',
    birthDate: '1978-04-16',
    yearOfExperience: 10,
    positionApplied: 'Orchestrator',
    applicationDate: '2018-06-19',
    status: 'waiting',
  },
  {
    id: 134,
    name: 'Remona Koss',
    email: 'johnnie@schoen.org',
    birthDate: '2000-06-23',
    yearOfExperience: 10,
    positionApplied: 'Specialist',
    applicationDate: '2017-12-27',
    status: 'waiting',
  },
  {
    id: 135,
    name: 'Sheba Brown',
    email: 'kristyn@kozey.io',
    birthDate: '1973-03-07',
    yearOfExperience: 13,
    positionApplied: 'Engineer',
    applicationDate: '2018-01-19',
    status: 'waiting',
  },
  {
    id: 136,
    name: 'Gregorio Glover',
    email: 'jana@von.io',
    birthDate: '1986-08-19',
    yearOfExperience: 11,
    positionApplied: 'Producer',
    applicationDate: '2018-04-09',
    status: 'approved',
  },
  {
    id: 137,
    name: 'Marnie Thompson',
    email: 'cecil@pagac.com',
    birthDate: '1969-09-02',
    yearOfExperience: 12,
    positionApplied: 'Associate',
    applicationDate: '2018-07-23',
    status: 'approved',
  },
  {
    id: 138,
    name: 'Jonah Tromp',
    email: 'barrett@rutherford.io',
    birthDate: '1984-09-24',
    yearOfExperience: 5,
    positionApplied: 'Architect',
    applicationDate: '2018-03-31',
    status: 'approved',
  },
  {
    id: 139,
    name: 'Twana Luettgen',
    email: 'mitchell@shanahan.name',
    birthDate: '1988-03-24',
    yearOfExperience: 11,
    positionApplied: 'Agent',
    applicationDate: '2017-11-13',
    status: 'rejected',
  },
  {
    id: 140,
    name: 'Jeremy Lindgren',
    email: 'jinny@lubowitzlockman.name',
    birthDate: '1972-12-20',
    yearOfExperience: 10,
    positionApplied: 'Designer',
    applicationDate: '2018-02-14',
    status: 'waiting',
  },
  {
    id: 141,
    name: 'Shemika Johnson',
    email: 'earlbecker@jacobihills.biz',
    birthDate: '1982-07-19',
    yearOfExperience: 6,
    positionApplied: 'Strategist',
    applicationDate: '2018-08-05',
    status: 'approved',
  },
  {
    id: 142,
    name: 'Beau Hudson',
    email: 'galina@hoegerohara.io',
    birthDate: '1988-07-06',
    yearOfExperience: 15,
    positionApplied: 'Producer',
    applicationDate: '2018-07-02',
    status: 'rejected',
  },
  {
    id: 143,
    name: 'Asa Volkman',
    email: 'bernardkautzer@murphy.biz',
    birthDate: '1971-07-01',
    yearOfExperience: 11,
    positionApplied: 'Executive',
    applicationDate: '2018-02-02',
    status: 'approved',
  },
  {
    id: 144,
    name: 'Maddie Hudson',
    email: 'asabeatty@gleichner.org',
    birthDate: '1985-06-17',
    yearOfExperience: 11,
    positionApplied: 'Supervisor',
    applicationDate: '2017-11-23',
    status: 'waiting',
  },
  {
    id: 145,
    name: 'Sharri Haag',
    email: 'aishakuhn@raynor.org',
    birthDate: '1990-09-15',
    yearOfExperience: 6,
    positionApplied: 'Director',
    applicationDate: '2018-02-07',
    status: 'approved',
  },
  {
    id: 146,
    name: 'Malcolm Spencer',
    email: 'clairglover@ruel.org',
    birthDate: '1973-05-15',
    yearOfExperience: 3,
    positionApplied: 'Associate',
    applicationDate: '2018-08-27',
    status: 'rejected',
  },
  {
    id: 147,
    name: 'Jacob Ruecker',
    email: 'claudio@sawayn.info',
    birthDate: '1973-06-24',
    yearOfExperience: 4,
    positionApplied: 'Administrator',
    applicationDate: '2018-02-12',
    status: 'waiting',
  },
  {
    id: 148,
    name: 'Shila Torphy',
    email: 'lonconsidine@beatty.biz',
    birthDate: '1983-08-15',
    yearOfExperience: 14,
    positionApplied: 'Consultant',
    applicationDate: '2018-01-20',
    status: 'waiting',
  },
  {
    id: 149,
    name: 'Roosevelt Walsh',
    email: 'celeste@schulistshanahan.co',
    birthDate: '1985-01-03',
    yearOfExperience: 10,
    positionApplied: 'Assistant',
    applicationDate: '2018-07-12',
    status: 'waiting',
  },
  {
    id: 150,
    name: 'Timothy Huel',
    email: 'karl@romaguerarunte.biz',
    birthDate: '1995-09-20',
    yearOfExperience: 14,
    positionApplied: 'Director',
    applicationDate: '2018-03-02',
    status: 'rejected',
  },
  {
    id: 151,
    name: 'Mr. Cedrick Greenfelder',
    email: 'meldakris@block.net',
    birthDate: '1996-10-10',
    yearOfExperience: 5,
    positionApplied: 'Specialist',
    applicationDate: '2017-10-15',
    status: 'waiting',
  },
  {
    id: 152,
    name: 'Evia Rau PhD',
    email: 'mistiebashirian@cronin.name',
    birthDate: '1999-04-02',
    yearOfExperience: 9,
    positionApplied: 'Technician',
    applicationDate: '2017-12-05',
    status: 'approved',
  },
  {
    id: 153,
    name: 'Dot Bosco DDS',
    email: 'jackierutherford@murazik.name',
    birthDate: '1999-11-11',
    yearOfExperience: 5,
    positionApplied: 'Designer',
    applicationDate: '2018-09-03',
    status: 'rejected',
  },
  {
    id: 154,
    name: 'Arthur Corwin',
    email: 'annelle@yundt.name',
    birthDate: '1993-09-17',
    yearOfExperience: 3,
    positionApplied: 'Technician',
    applicationDate: '2018-08-24',
    status: 'approved',
  },
  {
    id: 155,
    name: 'Vincent Gibson',
    email: 'stankulas@goyettecummings.name',
    birthDate: '2000-04-22',
    yearOfExperience: 3,
    positionApplied: 'Associate',
    applicationDate: '2017-12-19',
    status: 'approved',
  },
  {
    id: 156,
    name: 'Dalila Pouros',
    email: 'shariewiza@flatley.co',
    birthDate: '1974-10-17',
    yearOfExperience: 15,
    positionApplied: 'Consultant',
    applicationDate: '2018-06-28',
    status: 'rejected',
  },
  {
    id: 157,
    name: 'Scott Dach',
    email: 'jacinto@williamson.co',
    birthDate: '1986-05-01',
    yearOfExperience: 6,
    positionApplied: 'Assistant',
    applicationDate: '2018-01-11',
    status: 'waiting',
  },
  {
    id: 158,
    name: 'Miss Casey Mitchell',
    email: 'elvin@mayert.com',
    birthDate: '1991-04-27',
    yearOfExperience: 5,
    positionApplied: 'Supervisor',
    applicationDate: '2018-02-25',
    status: 'approved',
  },
  {
    id: 159,
    name: 'Jeneva Hettinger',
    email: 'corliemmerich@rathstehr.org',
    birthDate: '1974-05-18',
    yearOfExperience: 2,
    positionApplied: 'Associate',
    applicationDate: '2017-11-21',
    status: 'waiting',
  },
  {
    id: 160,
    name: 'Ms. Onita Simonis',
    email: 'maybelle@kemmerwaters.net',
    birthDate: '1985-10-30',
    yearOfExperience: 1,
    positionApplied: 'Technician',
    applicationDate: '2017-12-23',
    status: 'waiting',
  },
  {
    id: 161,
    name: 'Jose Orn',
    email: 'willenequigley@swaniawski.io',
    birthDate: '1992-12-31',
    yearOfExperience: 2,
    positionApplied: 'Designer',
    applicationDate: '2018-02-01',
    status: 'rejected',
  },
  {
    id: 162,
    name: 'Ms. Clare Heaney',
    email: 'rusty@baumbachboyle.name',
    birthDate: '1976-08-14',
    yearOfExperience: 1,
    positionApplied: 'Analyst',
    applicationDate: '2018-06-05',
    status: 'rejected',
  },
  {
    id: 163,
    name: 'Mr. Geoffrey Mueller',
    email: 'perryshanahan@hansen.name',
    birthDate: '2000-05-11',
    yearOfExperience: 6,
    positionApplied: 'Associate',
    applicationDate: '2018-02-14',
    status: 'waiting',
  },
  {
    id: 164,
    name: 'Lillian Morissette IV',
    email: 'chadledner@borer.com',
    birthDate: '1971-09-23',
    yearOfExperience: 1,
    positionApplied: 'Liaison',
    applicationDate: '2018-08-28',
    status: 'approved',
  },
  {
    id: 165,
    name: 'Brent Dach',
    email: 'randellbauch@dubuque.name',
    birthDate: '1988-05-08',
    yearOfExperience: 2,
    positionApplied: 'Orchestrator',
    applicationDate: '2018-05-25',
    status: 'approved',
  },
  {
    id: 166,
    name: 'Lacy Homenick',
    email: 'dede@raynorrempel.co',
    birthDate: '1971-07-10',
    yearOfExperience: 3,
    positionApplied: 'Director',
    applicationDate: '2018-04-19',
    status: 'rejected',
  },
  {
    id: 167,
    name: 'Pauletta Schaden',
    email: 'shaniqua@lueilwitzstamm.net',
    birthDate: '1975-05-05',
    yearOfExperience: 6,
    positionApplied: 'Strategist',
    applicationDate: '2018-03-26',
    status: 'approved',
  },
  {
    id: 168,
    name: 'Telma Tremblay',
    email: 'alesha@schmelermacejkovic.info',
    birthDate: '1998-02-06',
    yearOfExperience: 4,
    positionApplied: 'Executive',
    applicationDate: '2017-11-20',
    status: 'rejected',
  },
  {
    id: 169,
    name: 'Mr. Maye Gaylord',
    email: 'cherlittle@wymanrosenbaum.info',
    birthDate: '1983-12-08',
    yearOfExperience: 12,
    positionApplied: 'Analyst',
    applicationDate: '2017-12-17',
    status: 'approved',
  },
  {
    id: 170,
    name: 'Buster Krajcik',
    email: 'emmapouros@weber.io',
    birthDate: '1978-04-23',
    yearOfExperience: 11,
    positionApplied: 'Facilitator',
    applicationDate: '2018-03-08',
    status: 'approved',
  },
  {
    id: 171,
    name: 'Fritz Glover PhD',
    email: 'nedwaelchi@nader.com',
    birthDate: '2000-04-19',
    yearOfExperience: 10,
    positionApplied: 'Manager',
    applicationDate: '2018-04-07',
    status: 'rejected',
  },
  {
    id: 172,
    name: 'Madonna Gleichner',
    email: 'garretmills@mcclure.info',
    birthDate: '1969-08-22',
    yearOfExperience: 1,
    positionApplied: 'Planner',
    applicationDate: '2017-10-25',
    status: 'approved',
  },
  {
    id: 173,
    name: 'Sang Mosciski',
    email: 'charlie@bergstromjohns.io',
    birthDate: '1990-06-28',
    yearOfExperience: 4,
    positionApplied: 'Representative',
    applicationDate: '2018-07-20',
    status: 'waiting',
  },
  {
    id: 174,
    name: 'Chauncey Stokes',
    email: 'antoniettareilly@terrywitting.io',
    birthDate: '1976-10-16',
    yearOfExperience: 5,
    positionApplied: 'Producer',
    applicationDate: '2017-12-07',
    status: 'waiting',
  },
  {
    id: 175,
    name: 'Alta Jaskolski',
    email: 'peggy@bartell.co',
    birthDate: '1974-08-11',
    yearOfExperience: 1,
    positionApplied: 'Administrator',
    applicationDate: '2018-05-21',
    status: 'waiting',
  },
  {
    id: 176,
    name: "Delsie O'Connell",
    email: 'holli@dicki.net',
    birthDate: '1998-02-16',
    yearOfExperience: 15,
    positionApplied: 'Strategist',
    applicationDate: '2017-11-24',
    status: 'approved',
  },
  {
    id: 177,
    name: 'Corey Stokes',
    email: 'halley@barrows.io',
    birthDate: '1982-06-12',
    yearOfExperience: 5,
    positionApplied: 'Planner',
    applicationDate: '2018-03-08',
    status: 'rejected',
  },
  {
    id: 178,
    name: 'Mr. Logan Buckridge',
    email: 'savannafriesen@lehnerauer.co',
    birthDate: '1970-08-22',
    yearOfExperience: 9,
    positionApplied: 'Administrator',
    applicationDate: '2018-02-25',
    status: 'approved',
  },
  {
    id: 179,
    name: 'Geoffrey Bauch DDS',
    email: 'nenadoyle@roobhuel.info',
    birthDate: '1993-12-05',
    yearOfExperience: 9,
    positionApplied: 'Producer',
    applicationDate: '2017-12-26',
    status: 'waiting',
  },
  {
    id: 180,
    name: 'Clement Lynch',
    email: 'ardella@zulauf.org',
    birthDate: '1992-02-24',
    yearOfExperience: 14,
    positionApplied: 'Architect',
    applicationDate: '2017-12-23',
    status: 'approved',
  },
  {
    id: 181,
    name: 'Sonny Von',
    email: 'antonettahuels@hellerkulas.com',
    birthDate: '1969-09-26',
    yearOfExperience: 1,
    positionApplied: 'Assistant',
    applicationDate: '2018-07-14',
    status: 'rejected',
  },
  {
    id: 182,
    name: 'Shena Thiel',
    email: 'riley@hoppe.info',
    birthDate: '1987-10-06',
    yearOfExperience: 6,
    positionApplied: 'Representative',
    applicationDate: '2018-01-25',
    status: 'approved',
  },
  {
    id: 183,
    name: 'Matt Jacobs',
    email: 'yuki@tremblay.org',
    birthDate: '1983-01-13',
    yearOfExperience: 10,
    positionApplied: 'Supervisor',
    applicationDate: '2018-04-07',
    status: 'approved',
  },
  {
    id: 184,
    name: 'Isidro Crona',
    email: 'alannawaters@swaniawskiherman.info',
    birthDate: '1984-11-27',
    yearOfExperience: 2,
    positionApplied: 'Director',
    applicationDate: '2018-01-29',
    status: 'rejected',
  },
  {
    id: 185,
    name: "Miss Christoper O'Reilly",
    email: 'gloryborer@dare.co',
    birthDate: '1993-03-12',
    yearOfExperience: 15,
    positionApplied: 'Technician',
    applicationDate: '2018-02-12',
    status: 'waiting',
  },
  {
    id: 186,
    name: 'Annie Bernhard',
    email: 'amanda@davis.net',
    birthDate: '1984-06-15',
    yearOfExperience: 9,
    positionApplied: 'Developer',
    applicationDate: '2018-03-08',
    status: 'waiting',
  },
  {
    id: 187,
    name: 'Quincy Thiel',
    email: 'christeengreenfelder@christiansen.io',
    birthDate: '1991-07-01',
    yearOfExperience: 9,
    positionApplied: 'Executive',
    applicationDate: '2018-01-18',
    status: 'approved',
  },
  {
    id: 188,
    name: 'Dr. Alec Mraz',
    email: 'scottywisoky@predovicbuckridge.biz',
    birthDate: '1974-12-02',
    yearOfExperience: 1,
    positionApplied: 'Technician',
    applicationDate: '2018-03-11',
    status: 'waiting',
  },
  {
    id: 189,
    name: 'Ms. Matt Wyman',
    email: 'lili@king.com',
    birthDate: '1996-02-01',
    yearOfExperience: 11,
    positionApplied: 'Planner',
    applicationDate: '2018-08-13',
    status: 'approved',
  },
  {
    id: 190,
    name: 'Mr. Rayford Marvin',
    email: 'cathern@hahnwiegand.com',
    birthDate: '1993-09-17',
    yearOfExperience: 3,
    positionApplied: 'Strategist',
    applicationDate: '2018-03-22',
    status: 'rejected',
  },
  {
    id: 191,
    name: 'Cristie Skiles',
    email: 'adela@yost.biz',
    birthDate: '1975-09-18',
    yearOfExperience: 2,
    positionApplied: 'Designer',
    applicationDate: '2018-09-27',
    status: 'approved',
  },
  {
    id: 192,
    name: 'Mr. Olympia Homenick',
    email: 'denisha@oberbrunnerschumm.org',
    birthDate: '1994-04-04',
    yearOfExperience: 9,
    positionApplied: 'Agent',
    applicationDate: '2017-10-31',
    status: 'waiting',
  },
  {
    id: 193,
    name: 'Samantha Schimmel',
    email: 'cecilleframi@streich.com',
    birthDate: '1987-03-08',
    yearOfExperience: 4,
    positionApplied: 'Strategist',
    applicationDate: '2017-10-17',
    status: 'waiting',
  },
  {
    id: 194,
    name: 'Wilburn Beier',
    email: 'nildadare@blandalubowitz.biz',
    birthDate: '1999-04-11',
    yearOfExperience: 10,
    positionApplied: 'Analyst',
    applicationDate: '2018-01-28',
    status: 'approved',
  },
  {
    id: 195,
    name: 'Angel Stokes',
    email: 'oswaldosipes@fisher.net',
    birthDate: '1977-07-19',
    yearOfExperience: 4,
    positionApplied: 'Liaison',
    applicationDate: '2018-04-04',
    status: 'approved',
  },
  {
    id: 196,
    name: 'Shanita Wyman',
    email: 'galen@kohlerwitting.name',
    birthDate: '1989-01-07',
    yearOfExperience: 11,
    positionApplied: 'Representative',
    applicationDate: '2018-09-16',
    status: 'waiting',
  },
  {
    id: 197,
    name: 'Miss Twyla Beatty',
    email: 'johnette@witting.io',
    birthDate: '1978-06-27',
    yearOfExperience: 8,
    positionApplied: 'Manager',
    applicationDate: '2018-05-10',
    status: 'approved',
  },
  {
    id: 198,
    name: 'Laurinda Deckow V',
    email: 'denverconsidine@willms.io',
    birthDate: '1979-04-04',
    yearOfExperience: 1,
    positionApplied: 'Engineer',
    applicationDate: '2017-12-04',
    status: 'approved',
  },
  {
    id: 199,
    name: 'Mr. Alice Heller',
    email: 'aurelio@stoltenberg.biz',
    birthDate: '1971-01-21',
    yearOfExperience: 12,
    positionApplied: 'Agent',
    applicationDate: '2017-11-21',
    status: 'rejected',
  },
  {
    id: 200,
    name: 'Karla Maggio Jr.',
    email: 'efren@collinsrutherford.info',
    birthDate: '1980-09-02',
    yearOfExperience: 11,
    positionApplied: 'Facilitator',
    applicationDate: '2018-05-17',
    status: 'rejected',
  },
];

export const mockState = {
  candidatesApi: {
    candidates: mockCandidates,
    isLoading: false,
    error: undefined,
  },
  candidatesFilterSort: {
    sortBy: 'applicationDate',
    filterConfig: {
      name: 'vin',
      positionApplied: 'ass',
      status: '',
    },
  },
};
