openapi: 3.0.1
info:
  title: Personio tech test API
  description: OpenAPI 3.0 description of Personio tech test API
  version: "0.1"
servers:
  - url: "http://personio-fe-test.herokuapp.com"
paths:
  /api/v1/candidates:
    get:
      description: Retrieve list of candidates for Personio
      responses:
        "200":
          description: A list of candidates
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    $ref: "#/components/schemas/Candidates"
                  error:
                    $ref: "#/components/schemas/FatalError"
components:
  schemas:
    ApplicationStatus:
      type: string
      enum: ["approved", "rejected", "waiting"]
    Candidate:
      type: object
      required:
        - id
        - name
        - email
        - birth_date
        - years_of_experice
        - position_applied
        - application_date
        - status
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        email:
          type: string
        birth_date:
          type: string
        year_of_experience:
          type: integer
          format: int64
        position_applied:
          type: string
        application_date:
          type: string
        status:
          $ref: "#/components/schemas/ApplicationStatus"
    Candidates:
      type: array
      items:
        $ref: "#/components/schemas/Candidate"
    FatalError:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
